apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: ClusterIP
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    #nodePort: 21
    name: ftps
  - port: 21000
    targetPort: 21000
    #nodePort: 21
    name: ftps-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      hostNetwork: true
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never