kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  # ClusterIP: none
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
# type: Opaque
# data:
#   username: YWRtaW4=
#   password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_alpine
        imagePullPolicy: Never
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        env:
        - name: "DB_USER"
          value: "bruhuser"
        - name: "DB_PASS"
          value: "bruhpass"
        ports:
        - containerPort: 3306
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
