kind: Service
apiVersion: v1
metadata:
  name: nginx
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: onlyone
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # hostNetwork: true #FUCK THIS LINE
      containers:
      - name: nginx
        image: nginx_alpine
        imagePullPolicy: Never
        env:
        - name: SSH_USERNAME
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: password
