apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
  labels:
    app: telegraf-app
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-app
  template:
    metadata:
      labels:
        app: telegraf-app
    spec:
      containers:
      - name: telegraf
        image: telegraf_alpine
        ports:
        - containerPort: 4999
        imagePullPolicy: Never
        env:
          - name: INFLUX_USER
            value: telegraf
          - name: INFLUX_URL
            value: "http://influxdb-svc:8086"
          - name: INFLUX_SKIP_DATABASE_CREATION
            value: "false"
          - name: INFLUX_PASSWORD
            value: "pass"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-rbac
  namespace: default
rules:
- apiGroups: [ "", "extensions", "apps" ]
  resources: [ "daemonsets", "deployments", "endpoints", "ingresses", "nodes", "persistentvolumes", "persistentvolumeclaims", "pods", "services", "statefulsets" ]
  verbs: [ "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-rbac
  namespace: default
roleRef:
  kind: Role
  name: role-rbac
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
