apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  # labels:
  #   app: wordpress-deployment
spec:
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
  - name: wordpress
    port: 5050
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress
        image: wordpress_alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: pass
        - name: DB_NAME
          value: wordpress
        ports:
          - containerPort: 80
