apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: wordpress-secret
# type: Opaque
# data:
#   username: YWRtaW4=
#   password: YWRtaW4=
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      hostNetwork: true
      containers:
      - image: wordpress_alpine
        name: wordpress
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits: 
        #     memory: "256Mi"
        #     cpu: "500m"
        env:
        - name: "WORDPRESS_DB_HOST"
          value: "service-mysql.default.svc.cluster.local:3306"
        - name: "WORDPRESS_DB_USER"
          value: "bruhuser"
        - name: "WORDPRESS_DB_PASSWORD"
          value: "bruhpass"
        - name: "WORDPRESS_DB_NAME"
          value: "wordpress"
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: password
        # - name: WORDPRESS_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-secret
        #       key: username
        # - name: WORDPRESS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-secret
        #       key: password
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
